//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Property_ID { get; set; }
        public Nullable<int> Worker_ID { get; set; }
        public Nullable<System.DateTime> Rent_time { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual List_of_property List_of_property { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
